const Contact = [
  {
    id: 1,
    name: "Stefan Angel",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 2,
    name: "Sample Contact",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
  {
    id: 3,
    name: "Peter",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 4,
    name: "Angel",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
  {
    id: 5,
    name: "Rocky",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 6,
    name: "Megan",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
  {
    id: 7,
    name: "Ketty",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 8,
    name: "Inna",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
  {
    id: 9,
    name: "Foxie",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 10,
    name: "Lily",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
  {
    id: 11,
    name: "Foxie",
    number: "123-456-666",
    img: require("../assets/img/stefan.jpg"),
    about: "Service Holder",
    blood: "(A+)",
  },
  {
    id: 12,
    name: "Lily",
    number: "121-456-666",
    img: require("../assets/img/ayo.jpg"),
    about: "Service Holder",
    blood: "(B+)",
  },
];

export default Contact;
